# Este arquivo foi gerado automaticamente. NÃO EDITE MANUALMENTE.
# Gerado por: gerador_dicionario.py

ACOMPANHAMENTOS = [{'id': 'extra1', 'nome': 'Farofa'},
 {'id': 'extra2', 'nome': 'Vinagrete'},
 {'id': 'extra3', 'nome': 'Maionese da Casa'}]

PONTOS_CARNE = [{'id': 'mal', 'nome': 'Mal Passado'},
 {'id': 'ponto', 'nome': 'Ao Ponto'},
 {'id': 'bem', 'nome': 'Bem Passado'}]

CARDAPIO_PDV = [{'id': 1,
  'nome': 'Espetinhos',
  'ordem': 1,
  'produtos': [{'descricao': 'Corte nobre, macio e suculento, feito na brasa.',
                'foto_url': 'file_mignon.jpg',
                'id': 101,
                'nome': 'Filé Mignon',
                'preco_venda': 15.0,
                'produto_ordem': 1,
                'requer_preparo': 1},
               {'descricao': 'Carne saborosa com uma fina capa de gordura que '
                             'garante a suculência.',
                'foto_url': 'alcatra.jpg',
                'id': 102,
                'nome': 'Alcatra',
                'preco_venda': 12.0,
                'produto_ordem': 2,
                'requer_preparo': 1},
               {'descricao': 'Temperado com um toque especial da casa.',
                'foto_url': 'coracao.jpg',
                'id': 103,
                'nome': 'Coração de Frango',
                'preco_venda': 10.0,
                'produto_ordem': 3,
                'requer_preparo': 0},
               {'descricao': 'Cremoso por dentro e crocante por fora.',
                'foto_url': 'pao_alho.jpg',
                'id': 104,
                'nome': 'Pão de Alho',
                'preco_venda': 8.0,
                'produto_ordem': 4,
                'requer_preparo': 0}]},
 {'id': 2,
  'nome': 'Bebidas',
  'ordem': 2,
  'produtos': [{'descricao': 'Cerveja puro malte refrescante 330ml.',
                'foto_url': 'heineken.jpg',
                'id': 201,
                'nome': 'Heineken Long Neck',
                'preco_venda': 8.0,
                'produto_ordem': 1,
                'requer_preparo': 0},
               {'descricao': 'Lata 350ml.',
                'foto_url': 'brahma.jpg',
                'id': 202,
                'nome': 'Brahma Duplo Malte',
                'preco_venda': 7.0,
                'produto_ordem': 2,
                'requer_preparo': 0},
               {'descricao': 'Coca-Cola, Guaraná ou Fanta Laranja.',
                'foto_url': 'refri_lata.jpg',
                'id': 203,
                'nome': 'Refrigerante Lata',
                'preco_venda': 5.0,
                'produto_ordem': 3,
                'requer_preparo': 0}]}]
